### ISSUE TITLE
makefile failed with error code 2

### ISSUE THREAD

**Issue by rwyland** [bindle/iOSPorts#3]
After adding openLDAP to my project, adding target dependencies, linking libraries, and setting the search path for the include dir, I attempt to archive the openLDAP project and get the following:

**Makefile-cyrus-sasl**

```
/usr/bin/curl -O http://ftp.andrew.cmu.edu/pub/cyrus-mail/cyrus-sasl-2.1.23.tar.gz -o cyrus-sasl-2.1.23.tar.gz -s \
        || { rm -f cyrus-sasl-2.1.23.tar.gz; exit 1; };
/sbin/md5 cyrus-sasl-2.1.23.tar.gz > cyrus-sasl-2.1.23.tar.gz.md5
/usr/bin/diff cyrus-sasl-2.1.23.tar.gz.md5 build-aux/cyrus-sasl-2.1.23.tar.gz.md5 > /dev/null \
        || { /bin/rm -f cyrus-sasl-2.1.23.tar.gz.md5 cyrus-sasl-2.1.23.tar.gz; exit 1; };
make: *** [cyrus-sasl-2.1.23.tar.gz.md5] Error 1
Command /usr/bin/make failed with exit code 2
```

I'm using XCode 4.3.2 and building an iOS 5.1 iPad app in Lion.

Thanks

**Comment by rwyland** [comment]
My apologies, I didn't realize the makefiles were relying on the network.  It appears that something was being blocked on our  corporate firewall which was preventing me from FTPing the files.  Hopefully this will at least provide pointers for anyone else running into these issues.

Thanks

**Comment by syzdek** [comment]
Hi rwyland,  sorry about the delay, but I'm glad you were able to resolve the issue.  I've updated the README to mention that iOS Ports requires Internet Access to download the source packages.

**Comment by abbood** [comment]
actually even if there is a network connection.. the url provided (ie http://ftp.andrew.cmu.edu/pub/cyrus-mail/cyrus-sasl-2.1.23.tar.gz) is no good.. what i do in order to build IOSPorts is replace it with this (still valid) uri: http://ftp.kfki.hu/packages/mail/cyrus/cyrus-sasl-2.1.23.tar.gz
